-- AlterTable
ALTER TABLE `Capstone` MODIFY `status` ENUM('PENDING', 'PENDING_LECTURER', 'REJECTED_LECTURER', 'PENDING_FACULTY', 'REJECTED_FACULTY', 'DOING', 'SUBMITTED_FINAL', 'DEFENSE_ELIGIBLE', 'COMPLETED', 'FAILED') NOT NULL DEFAULT 'PENDING';
